language: php
php:
- 7.2
services:
- mysql
#before_install:
#- mysql -e 'CREATE DATABASE IF NOT EXISTS ckapi;'
before_script:
#- echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH
#  PRIVILEGES;\n" | mysql -u root
- composer install
script: "vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml"
